export { getBase64ImageFromURL } from './Base64Image';
export { createDocument1 } from './LetterOfEngagement';
export { createDocument2 } from './SecurityInductionAct';
export { createDocument3 } from './RealWorkEnviromentAct';
export { createDocument4 } from './EnterpriseProjectSchema';
export { createDocument5 } from './EnterpriceCertificate'
export { createDocument6 } from './LearningReport'
export { createDocument7 } from './BusinessEvaluation'
export { createDocument8 } from './AttendanceRecord'
export { createDocument9 } from './FrameworkPlanAndTraining-First'
export { createDocument10 } from './FrameworkPlanAndTraining-Second'
export { createDocument11 } from './FrameworkPlanAndTraining-Third'
export { createDocument12 } from './FrameworkPlanAndTraining-Fourth'
export { createDocument13 } from './FrameworkPlanAndTraining-Fifth'
