export { getBase64ImageFromURL } from './Base64Image';
export { createDocument2 } from './SecurityInductionAct';
export { createDocument1 } from './LetterOfEngagement';
export { createDocument3 } from './RealWorkEnviromentAct';
export { createDocument4 } from './EnterpriseProjectSchema';
export { createDocument5 } from './EnterpriceCertificate'
export { createDocument6 } from './LearningReport'
export { createDocument7 } from './BusinessEvaluation'
export { createDocument8 } from './InstituteEvaluation'
export { createDocument9 } from './AttendanceRecord'
